substitutions:
  # General substitutions:
  name: clack
  friendly_name: Clack
  device_description: "Esphome component for Clack WS1 softener without TOF sensor saltlevel detection"
  timezone: "Europe/Amsterdam"
  # Interval substitutions:
  salt_level_update_interval: 30s
  watermeter_update_interval: 600s # 10 minutes
  tank_percentage_update_interval: 600s
  clack_height_update_interval: 600s

### In order to use other language fix clack-label filename below:
### Currently supported languages are: en (English), nl (Dutch) and fr (French).
### ESP32-Atom-s3 is a M5STACK Atom s3 lite

packages:
  remote_package:
    url: https://github.com/fonske/clack-reader-v4
    ref: ws1_no_tof
    refresh: 0s
    files: [ 
      esphome/clack_ws1_no_tof/.clack-base.yaml,
      esphome/clack_ws1_no_tof/.clack-optional.yaml,
#      esphome/clack_ws1_no_tof/.clack-labels-nl.yaml,
      esphome/clack_ws1_no_tof/.clack-labels-en.yaml,
#      esphome/clack_ws1_no_tof/.clack-labels-fr.yaml,
      esphome/clack_ws1_no_tof/board-esp32-atom-s3.yaml,
    ]

### for developing/testing, uncomment local includes and comment out above remote_package packages part.
#packages:
##  substitutions: !include clack_ws1_no_tof/.clack-labels-en.yaml
#  substitutions: !include clack_ws1_no_tof/.clack-labels-nl.yaml
##  substitutions: !include clack_ws1_no_tof/.clack-labels-fr.yaml
#  device_base1:  !include clack_ws1_no_tof/board-esp32-atom-s3.yaml
#  device_base2:  !include clack_ws1_no_tof/.clack-base.yaml
#  device_base4:  !include clack_ws1_no_tof/.clack-optional.yaml

external_components:
  - source:
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]
    
time:
  - platform: sntp
    id: sntp_time
    timezone: ${timezone}
    # Enable this with your own NTP server if your device is on a no internet IOT lan. 
    #servers: 192.168.X.X
#    servers:
#     - 0.pool.ntp.org
#     - 1.pool.ntp.org
#     - 2.pool.ntp.org   

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: light
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"
    password: "configesp"
    ap_timeout: 15s

# Enable Over The Air Updates
ota:
  platform: esphome
#  password: !secret clack_ota_password

# Enable captive portal
captive_portal:
  
# Enable logger
logger:
  baud_rate: 0
  logs:
    esp32.preferences: DEBUG
    sensor: DEBUG
    text_sensor: DEBUG
    binary_sensor: DEBUG
    switch: DEBUG
    button: DEBUG
    number: DEBUG
    climate: DEBUG
    component: ERROR

# Enable Web server.
web_server:
  port: 80
